### ISSUE TITLE
How to save the currently loaded file using ofxEditor?

### ISSUE THREAD

**Issue by JoshuaBatty** [Akira-Hayasaka/ofxGLEditor#12]
Hi I see that oxGLEditor has a saveFile() method but I can't seem to work out how to call it from ofxEditor. 

I'm sure I must be missing something as it seems weird to be able to load a file into ofxEditor and not be able to save the result once you have modified it on screen.....? Cheers.

**Comment by danomatika** [comment]
ofxEditor is the core of the simple text editor while ofxGLEditor has the "bells and whistles". You can simply do a getText() into an ofBuffer and save it one line.

**Comment by JoshuaBatty** [comment]
Great thanks @danomatika. Much more usable now for my purposes.
