### ISSUE TITLE
Problems having ofxGLEditor and ofxFontStash addons in same project

### ISSUE THREAD

**Issue by JoshuaBatty** [Akira-Hayasaka/ofxGLEditor#15]
Hey i'm trying to upgrade my version of ofxGLEditor in my big project that also contains ofxFontStash. Obviously the 2 are using the fontstash library and it seems there are problems going on now. 

This is the error I am getting. 
![screen shot 2015-03-30 at 5 39 35 pm](https://cloud.githubusercontent.com/assets/1289413/6891410/a18cc0c0-d706-11e4-8cc0-74dcc287c0f3.png)

BTW, I have tried including just the fontstash lib from just armidilo's version of ofxFontEditor, or either from ofxGLEditor and the same errors come up. I have also tried this verison of ofxFontStash that apparently uses the newest version of fontstash... https://github.com/davetowey/ofxFontStash/tree/develop

 Any ideas? Cheers.

**Comment by danomatika** [comment]
That's duplicate symbols from stb_truetype.h. I'm using the newer version of fonststash and didn't want all the dependencies of ofxFontstash. Currently, you can't use both addons together. A simple solution is to remove one of the stb_typetype.h's from your project.

**Comment by JoshuaBatty** [comment]
Ok cheers for quick reply. I tried deleting the stb_typetype.h and same errors. Looks like ill have to find another addon that doesn't use fontstash in order to render vertical text.

**Comment by danomatika** [comment]
Even if you removed the file, you still need to clean the built objects. Try CMD+SHIFT+K, then rebuild.
