### ISSUE TITLE
End key moves cursor before the last character instead of *after* when it's on the last line

### ISSUE THREAD

**Issue by munshkr** [Akira-Hayasaka/ofxGLEditor#16]
If the cursor is on any other line except the last one, End key works OK. When the cursor is on the last line (or there is only one line), End key moves the cursor to the last character, but not after it. If you start writing, it writes everything before the last char.

![screenshot from 2015-04-03 11 57 14](https://cloud.githubusercontent.com/assets/4862/6983840/cfd50c36-d9f8-11e4-802e-749c8da41893.png) ![screenshot from 2015-04-03 11 58 23](https://cloud.githubusercontent.com/assets/4862/6983839/cfd186ec-d9f8-11e4-856d-73c6e7d1cb90.png)

Also, if the cursor is at the end, and you press Down to get to the last line, it moves before the last character too, so maybe the bug is not on the "End key handler" itself.

**Comment by danomatika** [comment]
Not surprising. I find I've been fixing a lot of little bigs like this form the original Fluxus implementation. Can you double check all the other cursor movement keys? I fixed page up/page down a few days ago, but I didn't test home and end.

**Comment by munshkr** [comment]
Yeah, I've seen the fixes about scrolling, great work! It looks much better.

I haven't bumped into other movement-related bugs for now, but I'll let you know. I'll also see if I can investigate further about this one.
