### ISSUE TITLE
"Flash" a text selection

### ISSUE THREAD

**Issue by munshkr** [Akira-Hayasaka/ofxGLEditor#18]
This is very useful for livecoding with languages that allow to evaluate string selections, not just whole script files, like SuperCollider or Tidal. It allows the user (and the audience) to know if specific part of the code on the screen has been evaluated just now.

I've implemented [something](https://github.com/munshkr/ofxGLEditor/commit/7178b3a6f78c20646f6c65e323cfcb8a151ef655) on my fork that looks like this:

![flash](https://cloud.githubusercontent.com/assets/4862/6990561/e4d7cafa-da44-11e4-9ba3-490cae0f7e8d.gif)

Mostly based on the `blowupCursor` and `drawSelectionCharBlock` functions. I haven't sent a PR yet because I'm not sure if it's in the scope of what ofxGLEditor offers. Do you think it's worthwhile to add this?

**Comment by danomatika** [comment]
Looks like a good idea. I'm reworking the syntax color schemes to support multiple languages and it would make sense to add this as an ofxEditorSettings option.

**Comment by danomatika** [comment]
I changed flashSelection to do the current highlight area and flashText for start & end positions.

**Comment by munshkr** [comment]
@danomatika awesome! thanks
