### ISSUE TITLE
[QUESTION] could this be used without the in screen editor but with an external text editor?

### ISSUE THREAD

**Issue by lewislepton** [Akira-Hayasaka/ofxGLEditor#21]
i like ofxGLEditor, but im more looking to use sublime text for my text editing instead, rather than the built in one when running the project.
so when i save the lua file ins sublime [or whatever text editor], it updates on screen.

im sure this could work, but would like to know if it could work with ofxGLEditor?

thanks

**Comment by danomatika** [comment]
Gotta say:

1. the forum is better for general questions, this is more for bugs/feature requests, etc
2. readmes & examples already exist:
  * https://vimeo.com/116370247   
  * https://github.com/Akira-Hayasaka/ofxGLEditor/tree/master/liveCodingExample
  * https://github.com/Akira-Hayasaka/ofxGLEditor#livecodingexample

**Comment by lewislepton** [comment]
no worries. have also asked on there. so just waiting. but thatnks for the links

**Comment by danomatika** [comment]
I don't subscribe to the forum, so you'll have to ping me with @danomatika or I won't get the notification email.
