### ISSUE TITLE
error compiling in  DELETE enum on UndoActionType @ Windows 10 and 0.9.8

### ISSUE THREAD

**Issue by moebiussurfing** [Akira-Hayasaka/ofxGLEditor#23]
hi @Akira-Hayasaka @danomatika ,
I have several errors related to the DELETE enum on UndoActionType in ofxEditor.h
```
		/// undo action types
		enum UndoActionType {
			INSERT,       //< text inserted
			REPLACE,      //< selection replaced via paste action
			OVERWRITE,    //< selection replaced via key input
			BACKSPACE,    //< text deleted to the left
			DELETE        //< text deletetd to the right
		};
```
![capture](https://user-images.githubusercontent.com/2106149/39951211-2aba2a44-555e-11e8-95b9-8df8642d593c.PNG)

I go to try a previous commit as the readme file points that the repo is build against OF current repo...
Any help is appreciated!

**Comment by moebiussurfing** [comment]
i downloaded the tagged zips 0.3.1 , 0.3.0 and I am getting the same above errors.
with the 0.2.0 zip i have other errors related to the font:
![capture](https://user-images.githubusercontent.com/2106149/39951681-7f0a8aea-5562-11e8-824d-597563a9510d.PNG)

**Comment by danomatika** [comment]
Try renaming DELETE to something else in the addon code. Also, the errors in your second screenshot look related to compiling the add-on with the OF git master. It's not been updated for that as we usually wait for full release versions to come out.

**Comment by moebiussurfing** [comment]
Thanks! It worked renaming DELETE to DELETE_RIGHT. Also I get another error and partially solved adding a missing ‘return PLAIN’ somewhere in an editorSyntax function. (I am on the cell phone and I can’t show you now)
Now it compiles but it crashes when moving the cursor to the end of text editor... Any idea?

**Comment by micuat** [comment]
a lazy fix is to add
```
#undef DELETE
```
after the `#include`s (I tested it with vs2015 + of0.9.8 + win10).

and yes, there is another error when
> crashes when moving the cursor to the end of text editor

**Comment by moebiussurfing** [comment]
Thanks. I am using the same setup:
0.9.8, Windows 10 and vs 2015.
I ll check to the cursor bug issue

**Comment by danomatika** [comment]
This should be fixed in the latest commits.
